/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2022-05-08 12:55:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class petinsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/styles.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/header.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/footer.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/pti.css\">\r\n");
      out.write("	\r\n");
      out.write("		<hr>\r\n");
      out.write("	\r\n");
      out.write("		<ul class=\"one\" position=fixed;>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("			<li><lable style=\"font-size:40px;  text-align: center;\">Happy Tails</lable></li>\r\n");
      out.write("			\r\n");
      out.write("			<li><a href=\"Home.html\">Home</a></li>\r\n");
      out.write("			<li><a href=\"view.jsp\">Members</a></li>\r\n");
      out.write("			<li><a href=\"viewPet.jsp\">Pets</a></li>\r\n");
      out.write("			<li><a href=\"VictoryViewAll\">Victory Log</a></li>\r\n");
      out.write("			<li><a href=\"stockview.jsp\">Stocks </a></li>\r\n");
      out.write("			<li><a href=\"About.html\">About Us</a></li>\r\n");
      out.write("			\r\n");
      out.write("		</ul>\r\n");
      out.write("		\r\n");
      out.write(" </head>\r\n");
      out.write(" <hr>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/petinsert.css\">\r\n");
      out.write("	<style>\r\n");
      out.write("	* {box-sizing: border-box}\r\n");
      out.write("\r\n");
      out.write("/* Add padding to containers */\r\n");
      out.write(".container {\r\n");
      out.write("  padding: 16px;\r\n");
      out.write("  position: center;\r\n");
      out.write("  \r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("form {\r\n");
      out.write("	\r\n");
      out.write("	display: inline-block; \r\n");
      out.write("    margin-left: 37%;\r\n");
      out.write("    margin-right:10%;\r\n");
      out.write("    width: 56%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("    width: 50%;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Full-width input fields */\r\n");
      out.write("input[type=text], input[type=DATE], input[type=number] {\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  padding: 15px;\r\n");
      out.write("  margin: 1px 0 10px 0;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  border: none;\r\n");
      out.write("  background: #f1f1f1;\r\n");
      out.write("  float: center;\r\n");
      out.write("  \r\n");
      out.write("   text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Overwrite default styles of hr */\r\n");
      out.write("hr {\r\n");
      out.write("  border: 1px solid #f1f1f1;\r\n");
      out.write("  margin-bottom: 25px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set a style for the submit/register button */\r\n");
      out.write(".submitbtn {\r\n");
      out.write("  background-color: 	 #008000;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 16px 20px;\r\n");
      out.write("  margin: 8px 0;\r\n");
      out.write("  border: none;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  opacity: 0.9;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submitbtn:hover {\r\n");
      out.write("  opacity:1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add a blue text color to links */\r\n");
      out.write("a {\r\n");
      out.write("  color: dodgerblue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".w3-button {width:150px;}\r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("  background-color: #26734d; /* Green */\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 15px 32px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  -webkit-transition-duration: 0.4s; /* Safari */\r\n");
      out.write("  transition-duration: 0.4s;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button3 {\r\n");
      out.write("  background-color:#26734d; /* Green */\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 15px 32px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  -webkit-transition-duration: 0.4s; /* Safari */\r\n");
      out.write("  transition-duration: 0.4s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button2:hover {\r\n");
      out.write("  align:center;\r\n");
      out.write("  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</style>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Pets Information</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-image: url(images/pet.jpg);background-repeat: no-repeat;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h6 style = \"text-align:center;font-size:30px;font-style:italic;color:red\">Pet Registration</h6>\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("<a href=\"viewPet.jsp\"><button class=\"button button2\">View Records</button></a>	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<form action=\"petinsert\" method=\"post\">\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("  <div class=\"form\" >\r\n");
      out.write("    <p style=\"background-image: H:\\Udaya itpm\\2\\Happy Tails\\src\\main\\webapp\\images\\1.jpg;\">\r\n");
      out.write("    \r\n");
      out.write("    <p>Please fill the form to register your pet.</p>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    <label for=\"name\"><b>Name</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"K.G.Kumara\" name=\"name\" id=\"name\" required >\r\n");
      out.write("\r\n");
      out.write("    <label for=\"phone\"><b>Phone</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"8xxxxxxxx/7xxxxxxxx\" pattern=\"[78]{1}[0-9]{8}\" name=\"phone\" id=\"phone\" required>\r\n");
      out.write("\r\n");
      out.write("    <label for=\"date\"><b>Date</b></label>\r\n");
      out.write("    <input type=\"date\" placeholder=\"Enter date\" name=\"date\" id=\"date\" required > \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <label for=\"category\"><b>Category</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Dogs\" name=\"category\" id=\"category\" required >\r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("    <label for=\"petname\"><b>Pet Name</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Dextor\" name=\"petname\" id=\"petname\"  required>\r\n");
      out.write("    \r\n");
      out.write("     <br>\r\n");
      out.write("    <label for=\"gender\"><b>Gender</b></label><br>\r\n");
      out.write("    <input type=\"radio\" id=\"male\" name=\"gender\" value=\"male\"  > <label for=\"male\">Male</label>\r\n");
      out.write("     <input type=\"radio\" id=\"female\" name=\"gender\" value=\"female\" > <label for=\"female\" >Female</label>\r\n");
      out.write("     \r\n");
      out.write("     <br>\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"age\"><b>Age</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Enter age\" name=\"age\" id=\"age\" required>\r\n");
      out.write("\r\n");
      out.write("    <label for=\"breed\"><b>Breed</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Rottweiler\" name=\"breed\" id=\"breed\" required  >\r\n");
      out.write("    \r\n");
      out.write("      <label for=\"dob\"><b>Date of Birth</b></label>\r\n");
      out.write("    <input type=\"date\" placeholder=\"Enter date\" name=\"dob\" id=\"dob\" required > \r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("    <!--  \r\n");
      out.write(" \r\n");
      out.write("    <label for=\"situation\"><b>Progress</b></label><br>\r\n");
      out.write("    \r\n");
      out.write("    <input type=\"radio\" id=\"situation\" name=\"situation\" value=\"Died\"> <label for=\"Died\">Died</label> <br>\r\n");
      out.write("    <input type=\"radio\" id=\"situation\" name=\"situation\" value=\"Recovered\"> <label for=\"Recovered\">Recovered</label><br>\r\n");
      out.write("    <input type=\"radio\" id=\"situation\" name=\"situation\" value=\"Under Treatment\"><label for=\"under_treatment\">Under Treatment</label><br>\r\n");
      out.write("    -->\r\n");
      out.write("    <br>\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("<button type=\"submit\" class=\"submitbtn\" >Submit</button>\r\n");
      out.write("\r\n");
      out.write("</form><br><br>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
