/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2022-05-08 12:44:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mysql.fabric.xmlrpc.base.Data;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.util.Date;

public final class stockReports_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1630844622000L));
    _jspx_dependants.put("jar:file:/C:/Users/DELL/Desktop/ITPM%20Intergrated/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HappyTailsVictoryLogs/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.mysql.fabric.xmlrpc.base.Data");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String id = request.getParameter("id");
String driver = "com.mysql.jdbc.Driver";
String connectionUrl = "jdbc:mysql://localhost:3306/";
String database = "happytailsdb";
String userid = "root";
String password = "";
try {
	Class.forName(driver);
} catch (ClassNotFoundException e) {
	e.printStackTrace();
}
Connection connection = null;
Statement statement = null;

ResultSet resultSet = null;
ResultSet resultSet1 = null;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.3/html2pdf.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>stocks Report</title>\r\n");
      out.write("<link rel = \"stylesheet\" href = \"Styles/vehicle/deco.css\">\r\n");
      out.write("<link rel = \"stylesheet\" href = \"Styles/vehicle/ieldset.css\">\r\n");
      out.write("<script src=\"JavaScriptSources/St_search.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("  table {\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("  }\r\n");
      out.write("  th, td {\r\n");
      out.write("    border: 2px solid black;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .back{\r\n");
      out.write("  \r\n");
      out.write("  		background-color:  	#D3D3D3;\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  fieldset{\r\n");
      out.write("	\r\n");
      out.write("	margin:50px 20px 20px 20px;\r\n");
      out.write("	width: 70%;\r\n");
      out.write("	border-color:black;\r\n");
      out.write("	 border-radius: 10px;\r\n");
      out.write("	\r\n");
      out.write("	background-color:#F8F8F8;\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- header -->\r\n");
      out.write("	<div class=\"header\">\r\n");
      out.write("		<center>\r\n");
      out.write("			<img alt=\"\" src=\"images/logo.jpg\" width =300px height=\"200px\">\r\n");
      out.write("		</center>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- <br><br>-->\r\n");
      out.write("<center>\r\n");
      out.write("\r\n");
      out.write("<fieldset> \r\n");
      out.write("	<center>\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("	</center>\r\n");
      out.write("	<!-- table -->\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("\r\n");
      out.write("<div id=\"list\">\r\n");
      out.write("\r\n");
      out.write("<p style=\"width: 50%;margin:0% 5%\">Date&Time:");
      out.print(new Date().toString());
      out.write(" </p>  \r\n");
      out.write("<center>\r\n");
      out.write("	<table>\r\n");
      out.write("	\r\n");
      out.write("	<h1>Stocks Report</h1>\r\n");
      out.write("		<tr >\r\n");
      out.write("		    <th><h3>Item ID<h3></th>\r\n");
      out.write("			<th><h3>Item Name<h3></th>\r\n");
      out.write("			<th><h3>Concerned Animal<h3></th>\r\n");
      out.write("			<th><h3>Item Size<h3></th>\r\n");
      out.write("			<th><h3>Unit Price(Rs.)<h3></th>\r\n");
      out.write("			<th><h3>Quantity<h3></th>\r\n");
      out.write("			<th><h3>Serial Number<h3></th>\r\n");
      out.write("			<th><h3>Coordinator Name<<h3></th>\r\n");
      out.write("			\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<br>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			<br><br>\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("		");

		try {
			String name = request.getParameter("name");

			connection = DriverManager.getConnection(connectionUrl + database, userid, password);
			statement = connection.createStatement();
			
		
				String sql = "select *  from stocks where name='" + name + "' ";
				resultSet = statement.executeQuery(sql);
				

				while (resultSet.next()) {

		
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("		\r\n");
      out.write("			<td>");
      out.print(resultSet.getString("id") );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(resultSet.getString("name") );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(resultSet.getString("animal") );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(resultSet.getString("size") );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(resultSet.getString("uprice") );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(resultSet.getString("quantity") );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(resultSet.getString("amount") );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(resultSet.getString("coordinator") );
      out.write("</td>\r\n");
      out.write("			\r\n");
      out.write("		</tr> \r\n");
      out.write("		");

		}
				
				String sql1 = "select COUNT(id) AS count from stocks where name='" + name + "' ";
				resultSet1 = statement.executeQuery(sql1);

				Float count;	
					
				if(resultSet1.next()){
					
					count =resultSet1.getFloat("count");

				}
				
				
      out.write("\r\n");
      out.write("				<tr class=\"back\">\r\n");
      out.write("				    <td><h4> Items count</h4> </td>\r\n");
      out.write("					<td><h4>");
      out.print(resultSet1.getString("count"));
      out.write("</h4></td>\r\n");
      out.write("					\r\n");
      out.write("					 \r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("				</tr>\r\n");
 				
				
			String sql2 = "select SUM(amount) AS new_amount  from stocks where name='" + name + "' ";
			resultSet = statement.executeQuery(sql2);
			Float New_amount;	
					
				if(resultSet.next()){
					New_amount=resultSet.getFloat("new_amount");
 				}

      out.write("\r\n");
      out.write("				<tr class=\"back\" >\r\n");
      out.write("				    <td><b> Budget</b> </td>\r\n");
      out.write("					<td><b><center>   ");
      out.print(resultSet.getString("new_amount"));
      out.write("</center></b></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("\r\n");
      out.write("	");

		connection.close();
		} catch (Exception e) {
		e.printStackTrace();
		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	</table>\r\n");
      out.write("	</center>\r\n");
      out.write("  </div> \r\n");
      out.write(" \r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("	<br>\r\n");
      out.write("	\r\n");
      out.write("</fieldset> \r\n");
      out.write("\r\n");
      out.write("<button onclick=\"print()\" class=\"button2\">Download  Report</button>\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<script >\r\n");
      out.write("	\r\n");
      out.write("	function print(){\r\n");
      out.write("	var element = document.getElementById(\"list\");\r\n");
      out.write("	var opt = {\r\n");
      out.write("	  margin:       1,\r\n");
      out.write("	  filename:     'Stocks report.pdf',\r\n");
      out.write("	  image:        { type: 'jpeg', quality: 0.98 },\r\n");
      out.write("	  html2canvas:  { scale: 2 },\r\n");
      out.write("	  jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }\r\n");
      out.write("	};\r\n");
      out.write("	 \r\n");
      out.write("	// New Promise-based usage:\r\n");
      out.write("	html2pdf().from(element).set(opt).save();\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
