/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2022-05-08 12:59:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;

public final class stockupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String id = request.getParameter("id");
String driver = "com.mysql.jdbc.Driver";
String connectionUrl = "jdbc:mysql://localhost:3306/happytailsdb";
String userid = "root";
String password = "";

try {
	Class.forName(driver);
} 
catch (ClassNotFoundException e) {
	e.printStackTrace();
}

Connection connection = null;
Statement statement = null;
ResultSet resultSet = null;

      out.write("\r\n");
      out.write("\r\n");

try{
	connection = DriverManager.getConnection(connectionUrl, userid, password);
	statement=connection.createStatement();
	String sql ="select * from stocks where id="+id;
	resultSet = statement.executeQuery(sql);
	while(resultSet.next()){

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"ISO-8859-1\">\r\n");
      out.write("	<title>Update</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"stockcss/styles.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"stockcss/header.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"stockcss/footer.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"stockcss/ptu.css\">\r\n");
      out.write("		<hr>\r\n");
      out.write("	\r\n");
      out.write("		<ul class=\"one\" position=fixed;>\r\n");
      out.write("		\r\n");
      out.write("			<li><lable style=\"font-size:40px;\">Happy Tail</lable></li>\r\n");
      out.write("			<li><a href=\"Home.html\">HOME</a></li>\r\n");
      out.write("<li><a href=\"view.jsp\">MEMBERS</a></li>\r\n");
      out.write("<li><a href=\"viewPet.jsp\">PETS</a></li>\r\n");
      out.write("<li><a href=\"VictoryViewAll.jsp\">VICTORY LOGS</a></li>\r\n");
      out.write("<li><a href=\"stockview.jsp\">STOCKS</a></li>\r\n");
      out.write("<li><a href=\"About.html\">ABOUT US</a></li>\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("		</ul>\r\n");
      out.write("		\r\n");
      out.write(" </head>\r\n");
      out.write(" <hr>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/stocksinsert.css\">\r\n");
      out.write("	<style>\r\n");
      out.write("	* {box-sizing: border-box}\r\n");
      out.write("\r\n");
      out.write("/* Add padding to containers */\r\n");
      out.write(".container {\r\n");
      out.write("  padding: 16px;\r\n");
      out.write("  position: center;\r\n");
      out.write("  \r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("form {\r\n");
      out.write("	margin: auto;\r\n");
      out.write("    \r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("    width: 90%;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Full-width input fields */\r\n");
      out.write("input[type=text], input[type=DATE], input[type=animal] {\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  padding: 15px;\r\n");
      out.write("  margin: 5px 0 22px 0;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  border: none;\r\n");
      out.write("  background: #f1f1f1;\r\n");
      out.write("  float: center;\r\n");
      out.write("  \r\n");
      out.write("   text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Overwrite default styles of hr */\r\n");
      out.write("hr {\r\n");
      out.write("  border: 1px solid #f1f1f1;\r\n");
      out.write("  margin-bottom: 25px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set a style for the submit/register button */\r\n");
      out.write(".submitbtn {\r\n");
      out.write("  background-color: red;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 16px 20px;\r\n");
      out.write("  margin: 8px 0;\r\n");
      out.write("  border: none;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  opacity: 0.9;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submitbtn:hover {\r\n");
      out.write("  opacity:1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add a blue text color to links */\r\n");
      out.write("a {\r\n");
      out.write("  color: dodgerblue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</style>		\r\n");
      out.write(" </head>\r\n");
      out.write(" <hr>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("<body style=\"\r\n");
      out.write("	background-image:url(file:///C:/Users/Fujitsu/eclipse-workspace/Happy/src/main/webapp/images/image1.jpg);\r\n");
      out.write("	background-repeat:no-repeat;\r\n");
      out.write("	background-postion:center;\r\n");
      out.write("	background-size:cover;\r\n");
      out.write("	margin:auto;\r\n");
      out.write("	max-width: 1000px;\r\n");
      out.write("	padding: 0px;\"\r\n");
      out.write("}>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("	<h1>Update Stock</h1>\r\n");
      out.write("	\r\n");
      out.write("  	<form action=\"stockupdate\" method=\"post\">\r\n");
      out.write("  	<input type=\"hidden\" name=\"patid\" value=\"");
      out.print(resultSet.getString("id") );
      out.write("\">\r\n");
      out.write("      	<label for=\"pid\">Item ID</label>\r\n");
      out.write("      		<input type=\"text\" name=\"id\"  value=\"");
      out.print(resultSet.getString("id") );
      out.write("\" readonly ><br>\r\n");
      out.write("\r\n");
      out.write("      	<label for=\"name\"><b>Item Name</b></label>\r\n");
      out.write("      		<input type=\"text\" name=\"name\" value=\"");
      out.print(resultSet.getString("name") );
      out.write("\" > <br>\r\n");
      out.write("\r\n");
      out.write("      	<label for=\"animal\" class=\"form-label\" >Concerned Animal</label> \r\n");
      out.write("		<select name=\"animal\" id=\"animals\" class=\"form-control text-uppercase\" >\r\n");
      out.write("			<option value=\"dog\">Dog</option>\r\n");
      out.write("			<option value=\"cat\">Cat</option>\r\n");
      out.write("			<option value=\"birds\">Birds</option>\r\n");
      out.write("			<option value=\"mouse\">Mouse</option>\r\n");
      out.write("			<option value=\"bunny\">Bunny</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		\r\n");
      out.write("		<label for=\"size\" class=\"form-label\">Item Size</label><br> \r\n");
      out.write("		<input type=\"radio\" id=\"small\" name=\"size\" value=\"SMALL\" checked>\r\n");
      out.write("		<label for=\"small\"  >SMALL</label>\r\n");
      out.write("		<input type=\"radio\" id=\"medium\" name=\"size\" value=\"MEDIUM\">\r\n");
      out.write("		<label for=\"medium\">MEDIUM</label>\r\n");
      out.write("		<input type=\"radio\" id=\"large\" name=\"size\" value=\"LARGE\">\r\n");
      out.write("		<label for=\"large\">LARGE</label><br>\r\n");
      out.write("      		\r\n");
      out.write("      	<label for=\"address\"><b>Unit Price(Rs.)</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"00.00\" name=\"uprice\" id=\"uprice\" value=\"");
      out.print(resultSet.getString("uprice") );
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"phone\"><b>Quantity</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"00\" name=\"quantity\" id=\"qty\" value=\"");
      out.print(resultSet.getString("quantity") );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("    <label for=\"date\"><b>Serial Number</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"00.00\" name=\"amount\" id=\"amt\" value=\"");
      out.print(resultSet.getString("amount") );
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"age\"><b>Coordinator name</b></label>\r\n");
      out.write("    <input type=\"text\" placeholder=\"mr.smith\" name=\"coordinator\" id=\"coordinator\" value=\"");
      out.print(resultSet.getString("coordinator") );
      out.write("\" readonly>\r\n");
      out.write("      		\r\n");
      out.write("  	<div class=\"row\">\r\n");
      out.write("    	<input type=\"submit\" value=\"Update\">\r\n");
      out.write(" 	 </div><br>\r\n");
      out.write(" 	 \r\n");
      out.write(" 	 <button type=\"button\" id=\"Back\"><a href=\"stockview.jsp\">Back</a></button>\r\n");
      out.write("	\r\n");
      out.write("	</form>\r\n");

}
connection.close();
} catch (Exception e) {
e.printStackTrace();
}

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
