/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2022-05-22 08:37:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class VictoryUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("input[type=text], select {\r\n");
      out.write("  width: 90%;\r\n");
      out.write("  font-size:20px;\r\n");
      out.write("  padding: 12px 20px;\r\n");
      out.write("  margin: 8px 0;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  border: 1px solid #ccc;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("input[type=date], select {\r\n");
      out.write("  width: 90%;\r\n");
      out.write("  font-size:20px;\r\n");
      out.write("  padding: 12px 20px;\r\n");
      out.write("  margin: 8px 0;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  border: 1px solid #ccc;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("input[type=number], select {\r\n");
      out.write("  width: 90%;\r\n");
      out.write("  font-size:20px;\r\n");
      out.write("  padding: 12px 20px;\r\n");
      out.write("  margin: 8px 0;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  border: 1px solid #ccc;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("input[type=submit] {\r\n");
      out.write("  width: 90%;\r\n");
      out.write("  background-color: #4CAF50;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 14px 20px;\r\n");
      out.write("  margin: 8px 0;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  font-size:30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("input[type=submit]:hover {\r\n");
      out.write("  background-color: blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div {\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  background-color: #f2f2f2;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("}\r\n");
      out.write(".button {\r\n");
      out.write("  background-color: #4CAF50; /* Green */\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 16px 32px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  transition-duration: 0.4s;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  margin-left:20cm;\r\n");
      out.write("  width:300px;\r\n");
      out.write("  height:50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button1 {\r\n");
      out.write("  background-color: white; \r\n");
      out.write("  color: black; \r\n");
      out.write("  border: 2px solid #4CAF50;\r\n");
      out.write("}\r\n");
      out.write(".button1:hover {\r\n");
      out.write("  background-color: red;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>	\r\n");
      out.write(" \r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"victoryCss/victory.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"victoryCss/styles.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"victoryCss/header.css\">\r\n");
      out.write("	\r\n");
      out.write(" \r\n");
      out.write(" <title> Update victory log</title>\r\n");
      out.write(" \r\n");
      out.write(" <header>	\r\n");
      out.write(" <hr>\r\n");
      out.write("\r\n");
      out.write("	<ul class=\"one\" position=fixed;>\r\n");
      out.write("\r\n");
      out.write("	<li><lable style=\"font-size:30px;\">HAPPY TAILS</lable></li>\r\n");
      out.write("<li><a href=\"Home.html\">HOME</a></li>\r\n");
      out.write("<li><a href=\"view.jsp\">MEMBERS</a></li>\r\n");
      out.write("<li><a href=\"viewPet.jsp\">PETS</a></li>\r\n");
      out.write("<li><a href=\"VictoryViewAll.jsp\">VICTORY LOGS</a></li>\r\n");
      out.write("<li><a href=\"stockview.jsp\">STOCKS</a></li>\r\n");
      out.write("<li><a href=\"About.html\">ABOUT US</a></li>\r\n");
      out.write("\r\n");
      out.write("	</ul>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write(" 	\r\n");
      out.write(" </head>\r\n");
      out.write("  <hr>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Connection for kobo table -->	\r\n");


try {
	String vlid = request.getParameter("vlid");
	Class.forName("com.mysql.jdbc.Driver");
	Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/happytailsdb","root","");
	String sql="Select * from victory where vlid="+vlid;
	Statement st=con.createStatement();
	ResultSet resultSet=st.executeQuery(sql);
	while(resultSet.next()){


      out.write("\r\n");
      out.write("	<div align=center id =\"bor\" style=\"background-image: url(victoryImages/victoryupdate.jpg);background-repeat: no-repeat;\" >\r\n");
      out.write("	\r\n");
      out.write("	<form action=\"victoryUpdate\" id = \"insertkobo\" method = \"post\" >\r\n");
      out.write("	<h1>UPDATE VICTORY LOG</h1><br/>\r\n");
      out.write("	<input type=\"hidden\" name=\"vlid\" value=\"");
      out.print(resultSet.getString("vlid") );
      out.write("\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- user inputs -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		Victory Log ID            :<input type = \"text\" name =\"vlid\"  value=\"");
      out.print(resultSet.getString("vlid") );
      out.write("\"  readonly><br><br>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("		Coordinator Name          :<input type = \"text\" name =\"cname\"  value=\"");
      out.print(resultSet.getString("cname") );
      out.write("\"readonly><br><br>\r\n");
      out.write("\r\n");
      out.write("		Program Type              :<input type = \"text\" name =\"program\"  value=\"");
      out.print(resultSet.getString("program") );
      out.write("\"><br><br>\r\n");
      out.write("	\r\n");
      out.write("	 	City Name                 :<input type = \"text\" name =\"city\"  value=\"");
      out.print(resultSet.getString("city") );
      out.write("\"><br><br>\r\n");
      out.write("	\r\n");
      out.write("		Location                  :<input type = \"text\" name =\"location\"  value=\"");
      out.print(resultSet.getString("location") );
      out.write("\"><br><br>\r\n");
      out.write("	\r\n");
      out.write("		Conducted Date            :<input type=\"date\" name=\"date\" id=\"dateWithMax\" value=\"");
      out.print(resultSet.getString("date") );
      out.write("\"><br><br>\r\n");
      out.write("								      		<script>\r\n");
      out.write("												var today = new Date();\r\n");
      out.write("												var dd = today.getDate();\r\n");
      out.write("												var mm = today.getMonth() + 1; //January is 0!\r\n");
      out.write("												var yyyy = today.getFullYear();\r\n");
      out.write("												if (dd < 10) {\r\n");
      out.write("								   					dd = '0' + dd;\r\n");
      out.write("												}\r\n");
      out.write("												if (mm < 10) {\r\n");
      out.write("								  	 				mm = '0' + mm;\r\n");
      out.write("												} \r\n");
      out.write("								    \r\n");
      out.write("												today = yyyy + '-' + mm + '-' + dd;\r\n");
      out.write("												document.getElementById(\"dateWithMax\").setAttribute(\"max\", today);\r\n");
      out.write("											</script>\r\n");
      out.write("	\r\n");
      out.write("		Budget (Rs.)               :<input type = \"number\" name =\"budget\"  value=\"");
      out.print(resultSet.getString("budget") );
      out.write("\"><br><br>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("		<input  type = \"submit\"  name = \"submit\" id = \"submit\" value = \"Update\" >\r\n");
      out.write("	\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<br> <br>\r\n");
      out.write("	<a href=\"VictoryViewAll.jsp\"><button  class=\"button button1\"><b>Cancel</b></button></a>	\r\n");
      out.write("		 <br>	\r\n");
      out.write("	 <br><br><br><br><br><br><br>	\r\n");
      out.write("	<br></div>\r\n");

}


}catch(Exception e)
{
e.printStackTrace();
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write(" <hr>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
