/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2022-05-08 12:36:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mysql.fabric.xmlrpc.base.Data;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.util.Date;

public final class VictoryPDF_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1630844622000L));
    _jspx_dependants.put("jar:file:/C:/Users/DELL/Desktop/ITPM%20Intergrated/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HappyTailsVictoryLogs/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.mysql.fabric.xmlrpc.base.Data");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Annual Victory Logs Report</title>\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"victoryCss/styles.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"victoryCss/header.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.3/html2pdf.bundle.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".button {\r\n");
      out.write("  background-color: #4CAF50; /* Green */\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 16px 32px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 15px;\r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  transition-duration: 0.4s;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  margin-left:18cm;\r\n");
      out.write("  width:150px;\r\n");
      out.write("  height:50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button1 {\r\n");
      out.write("  background-color: white; \r\n");
      out.write("  color: black; \r\n");
      out.write("  border: 2px solid #4CAF50;\r\n");
      out.write("}\r\n");
      out.write(".button1:hover {\r\n");
      out.write("  background-color: #cc0000;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write(" \r\n");
      out.write(" <header>	\r\n");
      out.write(" \r\n");
      out.write("		<hr>\r\n");
      out.write(" </header>	\r\n");
      out.write("<ul class=\"one\" position=fixed;>\r\n");
      out.write("\r\n");
      out.write("<li><lable style=\"font-size:30px;\">HAPPY TAILS</lable></li>\r\n");
      out.write("<li><a href=\"Home.html\">HOME</a></li>\r\n");
      out.write("<li><a href=\"view.jsp\">MEMBERS</a></li>\r\n");
      out.write("<li><a href=\"viewPet.jsp\">PETS</a></li>\r\n");
      out.write("<li><a href=\"VictoryViewAll.jsp\">VICTORY LOGS</a></li>\r\n");
      out.write("<li><a href=\"stockview.jsp\">STOCKS</a></li>\r\n");
      out.write("<li><a href=\"About.html\">ABOUT US</a></li>\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- <br><br>-->\r\n");
      out.write("<center>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"list\">\r\n");
      out.write("<center><img src =\"victoryImages/logo.jpg\" width =300px height=\"200px\" > </center>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table border =\"1\"><br>\r\n");
      out.write("	\r\n");
      out.write("	<h1>Annual Victory Logs Report</h1>\r\n");
      out.write("	<cenetr><p style=\"width: 50%; margin:0% 0%; align:left\";>Report generated Date and Time:");
      out.print(new Date().toString());
      out.write(" </p> </cenetr>  \r\n");
      out.write("		<tr tr style=\"background-color:#000099;color:white;font-size:20px;font-style: bold\" >\r\n");
      out.write("		    \r\n");
      out.write("			<th><b>Coordinator Name</b></th>\r\n");
      out.write("			<th><b>Program Type</b></th>\r\n");
      out.write("			<th><b>City Name</b></th>\r\n");
      out.write("			<th><b>Location</b></th>\r\n");
      out.write("			<th><b>Conducted Date</b></th>\r\n");
      out.write("			<th><b>Budget (Rs.)</b></th>\r\n");
      out.write("			<th><b>VLID</b></th>\r\n");
      out.write("			 \r\n");
      out.write("			\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");


	try {
		String year=request.getParameter("Year");
	
		Class.forName("com.mysql.jdbc.Driver");
		Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/happytailsdb","root","");
		String sql = "select *   from victory where date LIKE '"+year+"%'";
		Statement st=con.createStatement();
		ResultSet rs=st.executeQuery(sql);
		Connection connection = null;
		while(rs.next()){

	
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			\r\n");
      out.write("			<td>");
      out.print(rs.getString("cname"));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString("program"));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString("city"));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString("location"));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString("date"));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString("budget"));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString("vlid"));
      out.write("</td>\r\n");
      out.write("			 \r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		</tr> \r\n");
      out.write("\r\n");
      out.write("	");

		}

			String sql1 = "select SUM(budget) AS new_budget  from victory where date LIKE '"+year+"%'";
			rs = st.executeQuery(sql1);
			Float New_cost;	
					
				if(rs.next()){
					New_cost=rs.getFloat("new_budget");
 				}

      out.write("\r\n");
      out.write("				<tr style=\"background-color:#ffcccc;color:black\" >\r\n");
      out.write("				    <td><b>  Annual Budget (Rs.)</b> </td>\r\n");
      out.write("					<td><b><center>  ");
      out.print(rs.getString("new_budget"));
      out.write("/-</center></b></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
 				
				
			String sql2 = "select COUNT(vlid) AS new_count  from victory where date LIKE '"+year+"%'";
			rs = st.executeQuery(sql2);
			Float new_count;	
					
				if(rs.next()){
					New_cost=rs.getFloat("new_count");
 				}

      out.write("\r\n");
      out.write("				<tr style=\"background-color:#ffcccc;color:black\" >\r\n");
      out.write("				    <td><b>  No. of Annual Logs</b> </td>\r\n");
      out.write("					<td><b><center>   ");
      out.print(rs.getString("new_count"));
      out.write("</center></b></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("\r\n");
      out.write("	");

		connection.close();
		} catch (Exception e) {
		e.printStackTrace();
		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table><br><br>\r\n");
      out.write("<center>...................................<br>Signature</center>\r\n");
      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </div> \r\n");
      out.write(" \r\n");
      out.write("<br>		\r\n");
      out.write("\r\n");
      out.write("<center><button style= \"background-color:#e60000; COLOR:WHITE;\" onclick=\"print()\" >Download  Report</button></center>\r\n");
      out.write("<br><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("	<a href=\"VictoryViewAll.jsp\"><button  class=\"button button1\"><b>Cancel</b></button></a>	\r\n");
      out.write("		 <br>	\r\n");
      out.write("	 <br>\r\n");
      out.write("		<p>Copyright©2022 Happy Tails</p>\r\n");
      out.write("\r\n");
      out.write("<hr>	\r\n");
      out.write("	\r\n");
      out.write("	<script >\r\n");
      out.write("	\r\n");
      out.write("	function print(){\r\n");
      out.write("	var element = document.getElementById(\"list\");\r\n");
      out.write("	var opt = {\r\n");
      out.write("	  margin:       1,\r\n");
      out.write("	  filename:     'Annual Victory Logs Report.pdf',\r\n");
      out.write("	  image:        { type: 'jpeg', quality: 0.98 },\r\n");
      out.write("	  html2canvas:  { scale: 2 },\r\n");
      out.write("	  jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }\r\n");
      out.write("	};\r\n");
      out.write("	 \r\n");
      out.write("	// New Promise-based usage:\r\n");
      out.write("	html2pdf().from(element).set(opt).save();\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
