/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2022-05-23 12:54:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class VictoryViewAll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"victoryCss/victory.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"victoryCss/styles.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"victoryCss/header.css\">\r\n");
      out.write("	\r\n");
      out.write("<style>\r\n");
      out.write(".button {\r\n");
      out.write("  background-color: #4CAF50; \r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 10px 20px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  \r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  transition-duration: 0.4s;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  margin-left:20cm;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button1 {\r\n");
      out.write("  background-color: white; \r\n");
      out.write("  width:120px;\r\n");
      out.write("  height:45px;\r\n");
      out.write("  color: black; \r\n");
      out.write("  border: 2px solid #4CAF50;\r\n");
      out.write("  font-size: 15px;\r\n");
      out.write("  font-style: bold;\r\n");
      out.write("}\r\n");
      out.write(".button1:hover {\r\n");
      out.write("  background-color: #0000e6;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write(" \r\n");
      out.write(" <title> VICTORY LOGS </title>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("<ul class=\"one\" position=fixed;>\r\n");
      out.write("\r\n");
      out.write("<li><lable style=\"font-size:30px;\">HAPPY TAILS</lable></li>\r\n");
      out.write("<li><a href=\"Home.html\">HOME</a></li>\r\n");
      out.write("<li><a href=\"view.jsp\">MEMBERS</a></li>\r\n");
      out.write("<li><a href=\"viewPet.jsp\">PETS</a></li>\r\n");
      out.write("<li><a href=\"VictoryViewAll.jsp\">VICTORY LOGS</a></li>\r\n");
      out.write("<li><a href=\"stockview.jsp\">STOCKS</a></li>\r\n");
      out.write("<li><a href=\"About.html\">ABOUT US</a></li>\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("		\r\n");
      out.write(" 	\r\n");
      out.write(" </head>\r\n");
      out.write("\r\n");
      out.write(" <hr>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div align=center id =\"bor\" style=\"background-image: url(victoryImages/victorydelete.jpg);background-repeat: no-repeat;\">\r\n");
      out.write("<h1>VICTORY LOGS</h1>\r\n");
      out.write("	<BR>\r\n");
      out.write("		<form action=\"VictorySearch\" name=\"frm\" method=\"post\">\r\n");
      out.write("		<table align=\"center\">\r\n");
      out.write("			<tr>\r\n");
      out.write("			<td colspan=2 style=\"font-size:15pt;\" align=\"center\">\r\n");
      out.write("			<td><label for=\"fname\"><b style=\"font-size:20px;\">SEARCH VICTORY LOGS BY DATE :</b></label></td>\r\n");
      out.write("			<td><input type=\"date\" name=\"date\" id=\"dateWithMax\" required>\r\n");
      out.write("      		<script>\r\n");
      out.write("				var today = new Date();\r\n");
      out.write("				var dd = today.getDate();\r\n");
      out.write("				var mm = today.getMonth() + 1; //January is 0!\r\n");
      out.write("				var yyyy = today.getFullYear();\r\n");
      out.write("				if (dd < 10) {\r\n");
      out.write("   					dd = '0' + dd;\r\n");
      out.write("				}\r\n");
      out.write("				if (mm < 10) {\r\n");
      out.write("  	 				mm = '0' + mm;\r\n");
      out.write("				} \r\n");
      out.write("    \r\n");
      out.write("				today = yyyy + '-' + mm + '-' + dd;\r\n");
      out.write("				document.getElementById(\"dateWithMax\").setAttribute(\"max\", today);\r\n");
      out.write("			</script></td>\r\n");
      out.write("			<td><input   type=\"submit\" name=\"submit\" value=\"Search\" style= \"background-color:#e60000; COLOR:WHITE;width:70px;height:25px\"></td></tr>\r\n");
      out.write("			<br>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<BR>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("<table style = \"background-color:white\" border =\"2\"><br>\r\n");
      out.write("\r\n");
      out.write("<tr style=\"background-color:#000099;color:white;font-size:20px;font-style: bold\">\r\n");
      out.write("<th><b>Victory Log ID</b></th>\r\n");
      out.write("<th><b>Coordinator Name</b></th>\r\n");
      out.write("<th><b>Program Type</b></th>\r\n");
      out.write("<th><b>City Name</b></th>\r\n");
      out.write("<th><b>Location</b></th>\r\n");
      out.write("<th><b>Conducted Date</b></th>\r\n");
      out.write("<th><b>Budget(Rs.)</b></th>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<th>Update</th>\r\n");
      out.write("<th>Delete</th>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");


try {
	
	Class.forName("com.mysql.jdbc.Driver");
	Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/happytailsdb","root","");
	String sql="Select * from victory" ;
	Statement st=con.createStatement();
	ResultSet rs=st.executeQuery(sql);
	while(rs.next()){


      out.write("\r\n");
      out.write("<tr style=\"background-color:#e6e6ff;color:black;font-size:19px;font-style: bold\">\r\n");
      out.write("<td>");
      out.print(rs.getString(1));
      out.write("</td>\r\n");
      out.write("<td >");
      out.print(rs.getString(2));
      out.write("</td>\r\n");
      out.write("<td >");
      out.print(rs.getString(3));
      out.write("</td>\r\n");
      out.write("<td >");
      out.print(rs.getString(4));
      out.write("</td>\r\n");
      out.write("<td >");
      out.print(rs.getString(5));
      out.write("</td>\r\n");
      out.write("<td >");
      out.print(rs.getString(6));
      out.write("</td>\r\n");
      out.write("<td >");
      out.print(rs.getString(7));
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<td><a style= \"background-color: blue; color:white\"  href=\"VictoryUpdate.jsp?vlid=");
      out.print(rs.getString("vlid"));
      out.write("\" >UPDATE</a></td>\r\n");
      out.write("<td><a style= \"background-color: red; color:white\" href=\"VictoryDelete.jsp?vlid=");
      out.print(rs.getString("vlid"));
      out.write("\">DELETE</a></td>\r\n");
      out.write("</tr>\r\n");


}

}catch(Exception e)
{
e.printStackTrace();
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write(" <br>\r\n");
      out.write("	<a href=\"VictoryInsert.jsp\"><button  class=\"button button1\"><b>Add Logs</b></button></a>	\r\n");
      out.write("		 <br><br>\r\n");
      out.write("<br>\r\n");
      out.write("	<form action=\"VictoryPDF.jsp \" method=\"post\"  >	\r\n");
      out.write("		\r\n");
      out.write("    <b style=\"font-size:20px;\">Generate Annual Report :</b><input type = \"text\" name =\"Year\" id =\"Year\" placeholder = \"Year\"   required>\r\n");
      out.write("         <br><br>   \r\n");
      out.write("          <input style= \"background-color:#e60000; COLOR:WHITE;width:80px;height:30px\" type=\"submit\" value=\"Genarate\" >  \r\n");
      out.write("  </form>\r\n");
      out.write("<br><br>\r\n");
      out.write("<b style=\"font-size:20px;\">Generate All Victory Logs.Csv</b> <br><a href=\"VictoryReport\"><button style= \"background-color:#e60000; COLOR:WHITE;width:80px;height:30px\" ><b>Download</b></button></a>\r\n");
      out.write("<br><br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write(" <hr>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
