/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2022-05-08 12:21:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String id = request.getParameter("id");
String driverName = "com.mysql.jdbc.Driver";
String connectionUrl = "jdbc:mysql://localhost:3306/happytailsdb";
String userId = "root";
String password = "";

try {
Class.forName(driverName);
} catch (ClassNotFoundException e) {
e.printStackTrace();
}

Connection connection = null;
Statement statement = null;
ResultSet resultSet = null;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".button {\r\n");
      out.write("  background-color:#002699; /* Green */\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 15px 32px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  -webkit-transition-duration: 0.4s; /* Safari */\r\n");
      out.write("  transition-duration: 0.4s;\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".button2:hover {\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);\r\n");
      out.write("}\r\n");
      out.write(".viewtbl{\r\n");
      out.write("font-size:18px;\r\n");
      out.write("font-style:bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("	<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/styles.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/header.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/footer.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/view.css\">\r\n");
      out.write("	\r\n");
      out.write(" 	<title>View All</title>\r\n");
      out.write("\r\n");
      out.write("	<hr>\r\n");
      out.write("	\r\n");
      out.write("		<ul class=\"one\" position=center>\r\n");
      out.write("		\r\n");
      out.write("			<li><lable style=\"font-size:40px;\">Happy Tails</lable></li>\r\n");
      out.write("		<li><a href=\"Home.html\">Home</a></li>\r\n");
      out.write("			<li><a href=\"view.jsp\">Members</a></li>\r\n");
      out.write("			<li><a href=\"viewPet.jsp\">Pets</a></li>\r\n");
      out.write("			<li><a href=\"VictoryViewAll.jsp\">Victory Log</a></li>\r\n");
      out.write("			<li><a href=\"stockview.jsp\">Stocks </a></li>\r\n");
      out.write("			<li><a href=\"About.html\">About Us</a></li>\r\n");
      out.write("	\r\n");
      out.write("			\r\n");
      out.write("		</ul>\r\n");
      out.write("		\r\n");
      out.write("		<hr>\r\n");
      out.write(" 	\r\n");
      out.write(" </head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"background-image: url(images/pet.jpg);background-repeat: no-repeat;\">\r\n");
      out.write("<h6 style = \"text-align:center;font-size:40px;font-style:bold;color:red\">MEMBER RECORDS</h6><br><br>\r\n");
      out.write("	\r\n");
      out.write("	<div class=search>\r\n");
      out.write("		<form action=\"memberSearch\" name=\"frm\" method=\"post\">\r\n");
      out.write("		<table align=\"center\">\r\n");
      out.write("			<tr>\r\n");
      out.write("			<td colspan=2 style=\"font-size:12pt;\" align=\"center\">\r\n");
      out.write("			<td><label for=\"fname\">Search data by Name</label></td>\r\n");
      out.write("			<td><input type=\"text\" name=\"name\" ></td>\r\n");
      out.write("			<td><input  type=\"submit\" name=\"submit\" value=\"Search\"></td></tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("	</div>	\r\n");
      out.write("	\r\n");
      out.write("	<center>\r\n");
      out.write("	<table border=\"2\" class=\"viewtbl\">\r\n");
      out.write("	\r\n");
      out.write("	<tr style=\"background-color: #000099;color:white;text-align:center;\">\r\n");
      out.write("\r\n");
      out.write("		<td><b>ID</b></td>\r\n");
      out.write("		<td><b>Name</b></td>\r\n");
      out.write("		<td><b>NIC</b></td>\r\n");
      out.write("		<td><b>Contact Number</b></td>\r\n");
      out.write("		<td><b>Address</b></td>\r\n");
      out.write("		<td><b>Gender</b></td>\r\n");
      out.write("		<td><b>Date of Registration</b></td>\r\n");
      out.write("		<td><b>Employment type</b></td>\r\n");
      out.write("		<td><b>Annual Fee(Rs.)</b></td>\r\n");
      out.write("		\r\n");
      out.write("		<td><b>Update</b></td>\r\n");
      out.write("		<td><b>Delete</b></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("\r\n");

try{ 
connection = DriverManager.getConnection(connectionUrl, userId, password);
statement=connection.createStatement();
String sql ="SELECT * FROM member";

resultSet = statement.executeQuery(sql);
while(resultSet.next()){

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<td>");
      out.print(resultSet.getString("id") );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(resultSet.getString("name") );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(resultSet.getString("nic") );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(resultSet.getString("phone") );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(resultSet.getString("address") );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(resultSet.getString("gender") );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(resultSet.getString("date") );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(resultSet.getString("type") );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(resultSet.getString("fee") );
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<td><a href=\"updatemember.jsp?id=");
      out.print(resultSet.getString("id"));
      out.write("\" onClick=\"alert(' Update option in progress!')\">Update</a></td>\r\n");
      out.write("<td><a href=\"delete.jsp?id=");
      out.print(resultSet.getString("id"));
      out.write("\"onClick=\"alert(' Delete option in progress!')\">Delete</a></td>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
 
}

} catch (Exception e) {
e.printStackTrace();
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("</table><br>\r\n");
      out.write("<a href=\"memberinsert.jsp\"><button class=\"button button2\">Add Members</button></a>\r\n");
      out.write("</center><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("<center>\r\n");
      out.write("<a href=\"report\"><button class=\"btnget\">Download records</button>	\r\n");
      out.write("\r\n");
      out.write("<a href=\"reportsearch.jsp\"><button class=\"btnget\">Reports</button><br><br>	\r\n");
      out.write("\r\n");
      out.write("</center>									\r\n");
      out.write("<br><br><br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
